
import "./globals.css";
import "./lib/fontawesome";
import {ThemeProvider} from "./utils/ThemeProvider";
import {Providers} from "./Providers";


export const metadata = {
  title: "Reguadi Imad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>

      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"rel="stylesheet"/>
        <link href="https://api.fontshare.com/v2/css?f[]=clash-display@200,300,400,500,600,700,1&f[]=satoshi@300,301,400,401,500,501,700,701,900,901,1,2&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200..1000&family=El+Messiri:wght@400..700&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Alkalami&family=Aref+Ruqaa:wght@400;700&display=swap" rel="stylesheet">
    </link>
      </head>

      <body className="bg-white   dark:bg-black text-black dark:text-white ">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Providers>
            <main>{children}</main>
            
          </Providers>
        </ThemeProvider>
        
      </body>
    </html>
  );
}
